ShiningInfomation/ShiningInfomation/Controllers/AdminController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ShiningInfomation.Entity;
using System.Configuration;
using PagedList;
using PagedList.Mvc;
using System.Collections.Generic;

namespace ShiningInfomation.Controllers
{
    public class AdminController : Controller
    {
        private StudentInfoManagementEntities db = new StudentInfoManagementEntities();

        // GET: Admin
        public ActionResult Index(int? page)
        {
            var studentInfo = db.StudentInfo.Include(s => s.StudentID);
            //return View(studentInfo.ToList());

            int pageNumber = page ?? 1;
            int pageSize = 2;
            var persons = db.StudentInfo.ToList();
            return View(persons.ToPagedList(pageNumber, pageSize));
        }
     
    
        // GET: Admin/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentInfo studentInfo = db.StudentInfo.Find(id);
            if (studentInfo == null)
            {
                return HttpNotFound();
            }
            return View(studentInfo);
        }

        // GET: Admin/Create
        public ActionResult Create()
        {
            ViewBag.TeacherID = new SelectList(db.TeacherInfo, "TeacherID", "TeacherName");
            return View();
        }

        // POST: Admin/Create
       
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StudentID,StudentName,StudentAlias,Password,Team,Motto,TeacherID,GroupNum")] StudentInfo studentInfo)
        {
            if (ModelState.IsValid)
            {
                db.StudentInfo.Add(studentInfo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TeacherID = new SelectList(db.TeacherInfo, "TeacherID", "TeacherName", studentInfo.TeacherID);
            return View(studentInfo);
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentInfo studentInfo = db.StudentInfo.Find(id);
            if (studentInfo == null)
            {
                return HttpNotFound();
            }
            ViewBag.TeacherID = new SelectList(db.TeacherInfo, "TeacherID", "TeacherName", studentInfo.TeacherID);
            return View(studentInfo);
        }

        // POST: Admin/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Edit([Bind(Include = "StudentID,StudentName,StudentAlias,Password,Team,Motto,TeacherID,GroupNum")] StudentInfo studentInfo)
        //public ActionResult Edit([Bind(Include = "StudentID,StudentName,StudentAlias,Team,Motto,TeacherID,GroupNum")] StudentInfo studentInfo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(studentInfo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TeacherID = new SelectList(db.TeacherInfo, "TeacherID", "TeacherName", studentInfo.TeacherID);
            return View(studentInfo);
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentInfo studentInfo = db.StudentInfo.Find(id);
            if (studentInfo == null)
            {
                return HttpNotFound();
            }
            return View(studentInfo);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            StudentInfo studentInfo = db.StudentInfo.Find(id);
            db.StudentInfo.Remove(studentInfo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
   


}

ShiningInfomation/ShiningInfomation/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShiningInfomation.Entity;
using System.Data.Entity;
using PagedList;

namespace ShiningInfomation.Controllers
{
    public class SearchController : Controller
    {
        StudentInfoManagementEntities se = new StudentInfoManagementEntities();
        // GET: Search

        public DbSet<StudentInfo> Students { get; set; }
        private StudentInfoManagementEntities db = new StudentInfoManagementEntities();
      
        public ActionResult Search(string Search_name, string Search_team, string Search_group, int ? page)
        {
            if (!String.IsNullOrEmpty(Search_name) || !String.IsNullOrEmpty(Search_team) || !String.IsNullOrEmpty(Search_group))
            {
                var studentInfo = db.StudentInfo.Include(s => s.StudentID);
                //return View(studentInfo.ToList());

                int pageNumber = page ?? 1;
                int pageSize = 2;
                var persons = db.StudentInfo.ToList();
                return View(persons.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                var SearchList = from u in se.StudentInfo
                                 where 1 != 1
                                 select u;

                int pageNumber = page ?? 1;
                int pageSize = 2;
                var persons = db.StudentInfo.ToList();
                return View(persons.ToPagedList(pageNumber, pageSize));
             
            }
        }
    }
}

ShiningInfomation/ShiningInfomation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 闪亮四期学生信息管理系统</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("闪亮四期学生信息管理系统", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    <li>@Html.ActionLink("主页", "Index", "Index")</li>
                    <li>@Html.ActionLink("搜索信息", "Search", "Search")</li>
                    <li>@Html.ActionLink("管理员页", "Index", "Admin")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer></footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ShiningInfomation/ShiningInfomation/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div style="margin-bottom:10px;">
        <img src="~/Image/Login_header.PNG" />
    </div>
    <div style="position:absolute; ">
        @RenderBody()         
    </div>
    



</body>
</html>

ShiningInfomation/ShiningInfomation/Views/Shared/_SearchFenye.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>