ShiningInfomation/ShiningInfomation/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShiningInfomation.Controllers
{
    public class IndexController : Controller
    {
        // GET: Index
        public ActionResult Index()
        {
            return View();
        }
    }
}

ShiningInfomation/ShiningInfomation/Views/Admin/Create.cshtml
@model ShiningInfomation.Entity.StudentInfo

@{
    ViewBag.Title = "Create";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>新建学生信息</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StudentID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentAlias, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentAlias, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentAlias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Team, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Team, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Team, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Motto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Motto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Motto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherID, "TeacherID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TeacherID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TeacherID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ShiningInfomation/ShiningInfomation/Views/Admin/Delete.cshtml
@model ShiningInfomation.Entity.StudentInfo

@{
    ViewBag.Title = "Delete";
}



<div>
    <h3>删除学生信息</h3>
    <hr/>
    <dl class="dl-horizontal" style="">
        <dt>
            @Html.DisplayNameFor(model => model.StudentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentAlias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentAlias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Team)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Team)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Motto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Motto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeacherInfo.TeacherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeacherInfo.TeacherName)
        </dd>

    </dl>
    <hr />

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="margin-left:300px">
            <input type="submit" value="删除" class="btn btn-default" style="margin-bottom:10px" />
        </div>

        @Html.ActionLink("返回", "Index")

    }
</div>

ShiningInfomation/ShiningInfomation/Views/Admin/Details.cshtml
@model ShiningInfomation.Entity.StudentInfo

@{
    ViewBag.Title = "Details";
}


<div>
    <h3>学生信息</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StudentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentAlias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentAlias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Team)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Team)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Motto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Motto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeacherInfo.TeacherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeacherInfo.TeacherName)
        </dd>

    </dl>
</div>
<p style="margin-left:250px">

    @Html.ActionLink("编辑", "Edit", new { id = Model.StudentID }) |
    @Html.ActionLink("返回", "Index")
</p>

ShiningInfomation/ShiningInfomation/Views/Admin/Edit.cshtml
@model ShiningInfomation.Entity.StudentInfo

@{
    ViewBag.Title = "Edit";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <br/>
        <h3>学生信息</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.StudentID)

        <div class="form-group">
            @Html.LabelFor(model => model.StudentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentAlias, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentAlias, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentAlias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Team, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Team, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Team, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Motto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Motto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Motto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherID, "TeacherID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TeacherID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TeacherID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="保存" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ShiningInfomation/ShiningInfomation/Views/Admin/Index.cshtml
@model IEnumerable<ShiningInfomation.Entity.StudentInfo>


@{
    ViewBag.Title = "学生信息";
}

<h2>学生信息</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StudentName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StudentAlias)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Team)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Motto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GroupNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TeacherInfo.TeacherName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StudentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StudentAlias)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Team)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Motto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GroupNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TeacherInfo.TeacherName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.StudentID }) |
                @Html.ActionLink("Details", "Details", new { id = item.StudentID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.StudentID })
            </td>
        </tr>
    }
</table>

<center>@Html.Partial("_Fenye")</center>